const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "51960285930"
const SESSION_ID = "PRABATH-MD~CFlk0a6A#DhTg_VhzRKavpmC1pWz4XilXPu2lsMicJYimTYskEVs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
